#ifndef CONSTANTS
#define CONSTANTS
#define UNINITIALIZED_LONG (0xFFFFFFFFFFFFFFFF)
#define UNINITIALIZED_BYTE (0xFF)
#define UNINITIALIZED_WEIGHT (1.0F)
#define FIRST_REL_SOURCE_FLAG (00000010)
#define FIRST_REL_TARGET_FLAG (00000100)

#define BLOCK_SIZE (512)
#define PAGE_SIZE (512)
#endif
